### ISSUE TITLE
Silhouette Multiple Actions causes traceback - typeError: _ScrolledWindowBase.SetScrollbars(): argument 3 has unexpected type 'float'

### ISSUE THREAD

**Issue by ionsquare** [jnweiger/inkscape-silhouette#181]
First off, thank you to everyone who has contributed to this tool, it is incredible and has been working great using the `Export` > `Send to Silhouette...` option, but I'd love to get the multi action method working so I can do scoring and cutting in one go.

## Versions
Inkscape 1.1.2 (0a00cf5339, 2022-02-04, custom)
inkscape-silhouette - `master` branch - commit `7cfdd19` (current commit as of creating this issue)
OS: Arch
Device: Cameo 4

Installed with `make install-local`

I pulled the latest master and updated after seeing the same error on commit `52abd4d` from 2022-04-04.

## Steps to reproduce:
1. Export > Silhouette Multiple Actions
2. Click Apply on `Debugging/Logging Settings` window
3. `Silhouette Multi Log` window appears, showing the traceback

```
silhouette_multi.py was called via: ['silhouette_multi.py', '--dry_run=true', '--block=false', '--verbose=true', '/tmp/ink_ext_XXXXXX.svg2223K1']
Color keys are dict_keys(['colorless', [255, 0, 0], [0, 128, 0]])
save: None
Traceback (most recent call last):
  File "/home/username/.config/inkscape/extensions/silhouette_multi.py", line 910, in <module>
    e.run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "/home/username/.config/inkscape/extensions/silhouette_multi.py", line 774, in effect
    self.frame = SilhouetteMultiFrame(
  File "/home/username/.config/inkscape/extensions/silhouette_multi.py", line 325, in __init__
    self.init_actions()
  File "/home/username/.config/inkscape/extensions/silhouette_multi.py", line 595, in init_actions
    self.actions.SetItem(item)
  File "/usr/lib/python3.10/site-packages/wx/lib/agw/ultimatelistctrl.py", line 11256, in SetItem
    self._mainWin.SetItem(info)
  File "/usr/lib/python3.10/site-packages/wx/lib/agw/ultimatelistctrl.py", line 8781, in SetItem
    rectItem = self.GetItemRect(id)
  File "/usr/lib/python3.10/site-packages/wx/lib/agw/ultimatelistctrl.py", line 9564, in GetItemRect
    return self.GetSubItemRect(item, ULC_GETSUBITEMRECT_WHOLEITEM)
  File "/usr/lib/python3.10/site-packages/wx/lib/agw/ultimatelistctrl.py", line 9538, in GetSubItemRect
    self.RecalculatePositions(True)
  File "/usr/lib/python3.10/site-packages/wx/lib/agw/ultimatelistctrl.py", line 9632, in RecalculatePositions
    self.SetScrollbars(SCROLL_UNIT_X, lineHeight,
TypeError: _ScrolledWindowBase.SetScrollbars(): argument 3 has unexpected type 'float'
```
No further dialog appears after the log settings, just goes back to inkscape

I see there was some discussion about this feature being broken a while ago, but it looked like it was fixed in #156.

**Comment by t0b3** [comment]
did it work earlier for you? did you try on other systems than arch? what versions of python and wxpython do you have?

**Comment by ktosiek** [comment]
This is a bug in wxPython, and inkscape-silhouette can't do much about it.
Your version of WX doesn't work on Python 3.10. They have a fix, but it's not released yet: https://github.com/wxWidgets/Phoenix/commit/3eb9eb32dc3285435039f6c420c398665372a1ad.

It looks like Ubuntu 22.04 has Python 3.10 and wxPython 4.0.7, but they do carry patches for Py3.10 compatibility. Maybe Arch should take those patches too?

**Comment by ionsquare** [comment]
Thanks, it looks like the fix was made 6 months ago and still hasn't been released.

I ended up just finding `ultimatelistctrl.py` on my system and applied the patch myself and that fixed the issue for me. Thanks a bunch for the help!
