### ISSUE TITLE
error sending to cut

### ISSUE THREAD

**Issue by criarth** [jnweiger/inkscape-silhouette#209]
Hello, I installed the extension in inkscape 1.2.1 for mac Bigsur, but the following error is displayed:

Traceback (most recent call last):
  File "/Users/willian/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/sendto_silhouette.py", line 129, in <module>
    import inkex
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/__init__.py", line 11, in <module>
    from .extensions import *
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/extensions.py", line 34, in <module>
    from .elements import (
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/elements/__init__.py", line 10, in <module>
    from ._base import ShapeElement, BaseElement
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/elements/_base.py", line 38, in <module>
    from ..styles import Style, Classes
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/styles.py", line 33, in <module>
    from .css import ConditionalRule
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/css.py", line 27, in <module>
    import csselect
ModuleNotFoundError: No module named 'cssselect'

Any suggestions on how to fix this problem?

**Comment by t0b3** [comment]
not reproducible in CI. unable to take more actions due to lack of mac.
curious to hear from you wheter https://pypi.org/project/cssselect/ installing helps...

**Comment by criarth** [comment]
> não reprodutível em IC. incapaz de realizar mais ações devido à falta de mac. curioso para saber se https://pypi.org/project/cssselect/ instalação ajuda...

Thanks a lot for the quick reply. I used the following command - python3 -m pip install cssselect -
as described in (https://packaging.python.org/en/latest/tutorials/installing-packages/#use-pip-for-installing) and it worked, but when finishing the cut it displays the following message:

/usr/local/lib/python3.10/site-packages/usb1/__init__.py:2092: DeprecationWarning: Use "with USBContext() as context:" for safer cleanup on interpreter shutdown. See also USBContext.open().
  warnings.warn(
/Users/willian/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/sendto_silhouette.py:641: DeprecationWarning: inkex.deprecated.main.transform_mul -> Use @ operator instead
  transform = Transform(self.docTransform) * transform
/Users/willian/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/sendto_silhouette.py:642: DeprecationWarning: inkex.deprecated.main.transform_mul -> Use @ operator instead
  transform = Transform(extra_transform) * transform
Install matplotlib for python to allow graphical display of cuts

Sorry, but I couldn't interpret this message and I don't know what action to take to fix it.

**Comment by t0b3** [comment]
@criarth thanks for reporting. the deprecation warning doesn't harm. it has been addressed by 3a66e635c0d8bb369ebde697b4caa654853f2ecd
