### ISSUE TITLE
Write errors and inconsistent behavior

### ISSUE THREAD

**Issue by Mesil** [jnweiger/inkscape-silhouette#231]
I'm trying to send a job to my cameo 4 pro (which I believe is on the supported list) and I'm seeing some really inconsistent behavior that I can't make sense of.

About half the time I'll get a "No Graphtec Silhouette devices found" error and a third of the time I'll get what I assume is a permission error indicating that my user should be added to the lp group. The remainder of the time when the job apparently 'succeeds' based on the logs, I'm seeing what look to be errors sending data to the device.

Any idea what might be going on here or how to fix it? In many cases I'm seeing completely different errors without actually making changes on my end, just hitting "apply" again.

I've attached a log showing these behaviors over several runs. Below is the traceback from an attempt that doesn't error immediately.

`Traceback (most recent call last):
  File "/home/redpandasnugs/.config/inkscape/extensions/silhouette/Graphtec.py", line 749, in initialize
    self.send_escape(CMD_EOT)
  File "/home/redpandasnugs/.config/inkscape/extensions/silhouette/Graphtec.py", line 637, in send_escape
    self.write(CMD_ESC + esc, is_query=is_query) # Concatenation will typecheck
  File "/home/redpandasnugs/.config/inkscape/extensions/silhouette/Graphtec.py", line 597, in write
    raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
ValueError: write 2 bytes failed: r=0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/redpandasnugs/.config/inkscape/extensions/sendto_silhouette.py", line 1325, in <module>
    e.run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 231, in run
    self.save_raw(self.effect())
                  ^^^^^^^^^^^^^
  File "/home/redpandasnugs/.config/inkscape/extensions/sendto_silhouette.py", line 1223, in effect
    dev.setup(media=int(self.options.media, 10),
  File "/home/redpandasnugs/.config/inkscape/extensions/silhouette/Graphtec.py", line 899, in setup
    self.initialize()
  File "/home/redpandasnugs/.config/inkscape/extensions/silhouette/Graphtec.py", line 751, in initialize
    raise ValueError("Write Exception: %s, %s errno=%s\n\nFailed to write the first 3 bytes. Permissions? inf-wizard?" % (type(e), e, e.errno))
                                                                                                                                      ^^^^^^^
AttributeError: 'ValueError' object has no attribute 'errno'`
[send.log](https://github.com/fablabnbg/inkscape-silhouette/files/10832174/send.log)

**Comment by Mesil** [comment]
The behavior proved to be the product of a usb hardware error.
