### ISSUE TITLE
Preview fails with matplotlib 3.8.0

### ISSUE THREAD

**Issue by ictma** [jnweiger/inkscape-silhouette#268]
There is silent failure when running preview:
```
Install matplotlib for python to allow graphical display of cuts
Preview aborted.
```

On further inspection:
```
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
...
  File "/home/ave/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py", line 58, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/__init__.py", line 1, in <module>
    from .axes3d import Axes3D
  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/axes3d.py", line 23, in <module>
    from matplotlib import _api, cbook, docstring, _preprocess_data
ImportError: cannot import name 'docstring' from 'matplotlib' (/home/ave/.local/lib/python3.10/site-packages/matplotlib/__init__.py)

```

Could be conflict between user and site packages, but none the less using user matplotlib 3.7.0 works normally

**Comment by t0b3** [comment]
@ictma it looks like you mixed up your python environment. matplotlib 3.8.0 works perfectly fine here on gentoo.

**Comment by ictma** [comment]
> @ictma it looks like you mixed up your python environment. matplotlib 3.8.0 works perfectly fine here on gentoo.

It must be my local problem then, thanks I'll try to sort it out.
