### ISSUE TITLE
[Errno 13] Permission denied: 'C:\\Program Files\\Inkscape\\share\\inkscape\\extensions'

### ISSUE THREAD

**Issue by sprayed** [jnweiger/inkscape-silhouette#269]
Hi,
I'm so glad I found this tool, but I'm having some trouble getting it to work.
What does this error mean? The full error message from inkscape is below:

> Traceback (most recent call last):
>   File "sendto_silhouette.py", line 833, in <module>
>     e.run()
>   File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 123, in run
>     self.save_raw(self.effect())
>   File "sendto_silhouette.py", line 626, in effect
>     self.log = open(log_path, mode)
> PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Inkscape\\share\\inkscape\\extensions'

**Comment by t0b3** [comment]
@sprayed which version of the plugin do you run? how did you install it?

**Comment by sprayed** [comment]
> @sprayed which version of the plugin do you run? how did you install it?

I was using the latest version, newly downloaded to install this extension.
Inkscape version 1.0
inkscape-silhouette extension version 1.28
I followed the readme.md instructions for installing, libusb-win32 drivers installed with zadig 2.8

Since posting this issue I had to roll back to a previous system restore point. Zadig was not able to restore the drivers to the original (contrary to what the readme.md file said) and silhouette studio could not recognize any drivers other than the windows default one.

**Comment by t0b3** [comment]
@sprayed can you try with the latest version (trunk) with this commit included? https://github.com/fablabnbg/inkscape-silhouette/commit/91897ccbeb3cab62ed29fb144412b448dc64a2cd
