### ISSUE TITLE
Error when trying to apply settings

### ISSUE THREAD

**Issue by girrrrrrr2** [jnweiger/inkscape-silhouette#273]
Ive been at this for about 2 hours now and I dont know what ive done incorrectly. It loads I get all the dialog boxes I could ever want to mess with.. but then when i hit apply a little blank white window pops up, and then it locks up for about 10 seconds and then an error comes up. 

Traceback (most recent call last):
  File "C:\Program Files\Inkscape\share\inkscape\extensions\sendto_silhouette.py", line 753, in <module>
    e.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 250, in run
    self.save_raw(self.effect())
  File "C:\Program Files\Inkscape\share\inkscape\extensions\sendto_silhouette.py", line 648, in effect
    state = dev.status()  # hint at loading paper, if not ready.
  File "C:\Program Files\Inkscape\share\inkscape\extensions\silhouette\Graphtec.py", line 694, in status
    self.send_escape(CMD_ENQ, is_query=True)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\silhouette\Graphtec.py", line 637, in send_escape
    self.write(CMD_ESC + esc, is_query=is_query) # Concatenation will typecheck
  File "C:\Program Files\Inkscape\share\inkscape\extensions\silhouette\Graphtec.py", line 597, in write
    raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
ValueError: write 2 bytes failed: r=0

[inkscape cutter.log](https://github.com/fablabnbg/inkscape-silhouette/files/13211683/inkscape.cutter.log)

Pyusb is installed, driver overwrote.. I honestly dont even know whats left

**Comment by girrrrrrr2** [comment]
If i run multiple actions and dry run and verbose logging it errors out with 

Traceback (most recent call last):
  File "C:\Program Files\Inkscape\share\inkscape\extensions\silhouette_multi.py", line 272, in <module>
    if unblock_inkscape: pid = os.fork()
AttributeError: module 'os' has no attribute 'fork'

**Comment by t0b3** [comment]
@girrrrrrr2 just to exclude the obvious: did you load the media ?

**Comment by girrrrrrr2** [comment]
> @girrrrrrr2 just to exclude the obvious: did you load the media ?

yes, its also a  Quickutz Silhouette SD, I know its taking commands because vinyl master is sending it commands and its moving but the scale is hugely off.

**Comment by girrrrrrr2** [comment]
Ive decided to swap out the controller board and use a rumba that I had laying around combined with marlin to control it. Seems easier.

with that being said, I might have found the issue, there appears to be some sorta sensor in the cutting head, looks like its for sheet detection. 
Maybe that was faulty or something. It kinda looks like a photo sensor. I cant find anything about it online though.

Thing is kinda weird inside. 12v solenoid on the head. 24v 3.75 degree steppers, weird gearing... 

Thanks for the assistance!
