### ISSUE TITLE
Need help OSX Sonoma

### ISSUE THREAD

**Issue by Wolf6645** [jnweiger/inkscape-silhouette#278]
Hi, I need help because I'm completely lost. The plugin is installed and running in inkscape. But when I try to send it to plotter I end up with an error 
```
Traceback (most recent call last):
  File "/Users/wolf/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/sendto_silhouette.py", line 52, in <module>
    from silhouette.Graphtec import SilhouetteCameo, CAMEO_MATS
  File "/Users/wolf/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/silhouette/Graphtec.py", line 38, in <module>
    import usb1, usb.core
ModuleNotFoundError: No module named 'usb1'

```
I have absolutely no knowledge of Python :D

**Comment by t0b3** [comment]
See README instructions
