### ISSUE TITLE
<frozen importlib._bootstrap>:671: ImportWarning: DynamicImporter.exec_module() not found; falling back to load_module()

### ISSUE THREAD

**Issue by CatherineLE** [jnweiger/inkscape-silhouette#302]
Hi,

When I try to send my design to silhouette portrait 3 but  I have this error message (see below).

I have python 3.10.12
and
matplotlib              3.8.2
matplotlib-inline       0.1.3

![Screenshot from 2024-07-26 18-06-23](https://github.com/user-attachments/assets/6782a253-3c4d-445c-8b56-3339d36ff1f4)

<frozen importlib._bootstrap>:671: ImportWarning: DynamicImporter.exec_module() not found; falling back to load_module()
<frozen importlib._bootstrap>:671: ImportWarning: DynamicImporter.exec_module() not found; falling back to load_module()
Traceback (most recent call last):
  File "/usr/share/inkscape/extensions/sendto_silhouette.py", line 753, in <module>
    e.run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 250, in run
    self.save_raw(self.effect())
  File "/usr/share/inkscape/extensions/sendto_silhouette.py", line 648, in effect
    state = dev.status()  # hint at loading paper, if not ready.
  File "/usr/share/inkscape/extensions/silhouette/Graphtec.py", line 694, in status
    self.send_escape(CMD_ENQ, is_query=True)
  File "/usr/share/inkscape/extensions/silhouette/Graphtec.py", line 637, in send_escape
    self.write(CMD_ESC + esc, is_query=is_query) # Concatenation will typecheck
  File "/usr/share/inkscape/extensions/silhouette/Graphtec.py", line 597, in write
    raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
ValueError: write 2 bytes failed: r=0

Anyone has an idea how to fix this ? Thanks !

**Comment by t0b3** [comment]
@CatherineLE one very likely reason is the communication with the plotter is broken for some reason...
